### ISSUE TITLE
noteevent table equivalent in mimic-iv

### ISSUE THREAD

**Issue by tsonika** [YIKUAN8/MIMIC-IV-Postgres#3]
Hi,

Just wanted to check what would be the equivalent of MIMIC-III "noteevents" table in MIMIC-IV. I have downloaded the 1.0 and it has 4 modules i.e. ED, ICU, HOSP, and CORE.

Thank you!

**Comment by yikuan8** [comment]
Nothing. MIMIC IV doesn't contain any clinical notes up to the latest release.

**Comment by Xufeng-gif** [comment]
Hi,

Really hope you can add the code of creating PostgreSQL concepts of mimic-iv for I tried many times with the official code but failed.
Thank you very much!

**Comment by yikuan8** [comment]
@Xufeng-gif not quite understand your issue, this repo is for the installation of MIMIC IV to postgresql.

**Comment by mathurtanvi** [comment]
Hi,

Just wanted to check what would be the equivalent of MIMIC-III "noteevents" table in MIMIC-IV. I have downloaded the 2.2 and it has 3 modules i.e. ED, ICU, HOSP.
Can you guide me which tables to consider
Thank you!
